"""
Final gap fill - add more queries for intents still below target to reach 10,000.
"""
import os, json, random, pandas as pd
from collections import Counter

WS = r"c:\Users\Anupam Dasgupta\Desktop\INQSYT"
V2_FILE = os.path.join(WS, "Main_Data", "classifier_training_dataset_v2.csv")
EVAL_FILE = os.path.join(WS, "Main_Data", "eval_dataset.csv")
INTENTS_FILE = os.path.join(WS, "Main_Data", "intents_schema.json")
TARGET = 10000

v2_df = pd.read_csv(V2_FILE)
eval_df = pd.read_csv(EVAL_FILE)
with open(INTENTS_FILE) as f:
    intents_schema = json.load(f)

intent_names = [it["intent"] for it in intents_schema]
counts = Counter(v2_df["intent label"].tolist())
existing = set(v2_df["question"].str.lower().str.strip().tolist())
existing.update(eval_df["question"].str.lower().str.strip().tolist())
target_per = TARGET // len(intent_names)
gap = TARGET - len(v2_df)
print(f"Current: {len(v2_df)}, Gap: {gap}")

EXTRA_TEMPLATES = {
    "report_payment_scam": [
        "How do I report a payment scam to Amazon?",
        "Someone tricked me into buying Amazon gift cards for a scam",
        "I fell for a scam using Amazon Pay - what do I do?",
        "How to report fraudulent charges on Amazon?",
        "I was scammed through an Amazon seller payment request",
        "How to protect myself from Amazon gift card scams?",
        "Someone is requesting wire transfer claiming to be Amazon",
        "I received a scam call asking for Amazon gift card codes",
        "How to report a fraudulent Amazon seller to Amazon?",
        "What are common Amazon payment fraud schemes?",
        "I was asked to pay for a product outside of Amazon checkout",
        "How do I get my money back from an Amazon payment scam?",
        "Someone used my account to make fraudulent purchases",
        "How to report a romance scam that involved Amazon payments?",
        "I was tricked into sending Amazon gift cards to a scammer",
        "How to identify and report Amazon marketplace fraud?",
        "What should I do if I shared my Amazon payment info with a scammer?",
        "I received a scam asking me to verify payment via Amazon",
        "How to report a tech support scam involving Amazon?",
        "Someone impersonating Amazon asked me to pay via gift cards",
        "How do I report a counterfeit product scam on Amazon?",
        "I was victimized by an Amazon delivery payment scam",
        "How to report financial fraud connected to my Amazon account?",
        "What are the latest payment scam trends involving Amazon?",
        "I accidentally sent payment to a scam Amazon listing",
        "How to secure my account after a payment scam?",
        "I was asked to pay a customs fee to release my Amazon order",
        "How to report a Zelle or Venmo scam linked to Amazon?",
        "Someone is running a refund scam through Amazon returns",
        "How do I report a prize scam that asked for Amazon payment?",
        "I was scammed by a fake Amazon customer service agent",
        "How to get Amazon's help after falling for a payment scam?",
        "What is Amazon's policy on protecting buyers from scams?",
        "I sent money to a scammer pretending to sell on Amazon",
        "How to report a cryptocurrency scam involving Amazon?",
        "Someone used a stolen credit card on my Amazon account",
        "How do I report an investment scam that used Amazon's name?",
        "I was scammed by a fake Amazon lottery payment request",
        "How to recognize and avoid Amazon marketplace payment scams?",
        "I transferred money via bank for an Amazon product that never arrived",
        "How do I dispute a fraudulent Amazon transaction with my bank?",
        "Someone is using my Amazon identity for fraudulent payments",
        "How to report a subscription scam on Amazon?",
        "I was overcharged by a scam seller on Amazon",
        "How to report a fake charity donation scam on Amazon?",
        "Someone stole my Amazon gift card balance",
        "How to report a fake Amazon verification payment request?",
        "I was scammed by a phony Amazon affiliate program",
        "How do I report a multi-level marketing scam on Amazon?",
        "I purchased a product that turned out to be a scam listing",
        "How to report a bait-and-switch scam on Amazon?",
        "Someone is using my identity for Amazon Marketplace fraud",
        "I was scammed by a fake Amazon Prime payment request",
        "How to report a money mule scheme involving Amazon?",
        "Someone asked me to pay for shipping separately from Amazon",
        "How do I report a fake Amazon warranty scam?",
        "I was charged for a service I never authorized on Amazon",
        "How to report an advance fee fraud using Amazon?",
        "Someone created a fake Amazon store to scam buyers",
        "How do I get compensation after an Amazon payment scam?",
        "I received a package I didn't order as part of a brushing scam",
        "How to report a social media scam advertising Amazon deals?",
        "Someone tricked me into paying outside the Amazon platform",
        "How to file a police report for an Amazon-related payment scam?",
        "I was scammed through a fake Amazon product insurance scheme",
        "How do I report wire fraud related to Amazon purchases?",
        "Someone is running a pyramid scheme using Amazon's platform",
        "I fell for a QR code scam linked to a fake Amazon payment page",
        "How to protect my bank account after an Amazon payment scam?",
        "Someone stole my Amazon one-click payment information",
        "How do I report an unauthorized charge from an Amazon app?",
        "I was scammed by a fake Amazon Trade-In program",
        "How to report a fake seller verification payment request?",
        "Someone is misusing my Amazon credit card rewards",
        "How do I report an employment scam that uses Amazon's name?",
        "I was scammed by a fake Amazon Same-Day delivery payment",
        "How to prevent future scams on my Amazon payment methods?",
        "Someone charged my card through a fake Amazon API",
        "How to report a billing scam from a fake Amazon third-party?",
        "I was tricked into buying refurbished items at new prices",
        "How do I report a shipping insurance scam on Amazon?",
        "Someone is running a drop-shipping scam using my Amazon account",
        "How to get a refund from Amazon for a scam purchase?",
        "I was contacted by a scammer about an Amazon payment dispute",
        "How to report a fake Amazon price guarantee scam?",
        "Someone defrauded me through an Amazon Handmade listing",
        "How to report a fake Amazon flash sale payment scam?",
        "I was victimized by a fake Amazon customer rewards program",
        "How to report unauthorized access leading to payment fraud?",
        "Someone is using stolen photos for scam listings on Amazon",
        "How do I report a tax refund scam involving Amazon?",
        "I was scammed by a fake Amazon account upgrade payment",
        "How to file a complaint about Amazon payment fraud?",
        "Someone made purchases with my saved Amazon payment method",
        "How do I report a fake Amazon loyalty program scam?",
        "I was scammed through a fake Amazon account recovery payment",
        "How to safeguard my Amazon Wallet from scam charges?",
        "Someone created a fraudulent return to steal my payment",
        "How do I report a fake Amazon sweepstakes payment scam?",
        "I was scammed by a fake Amazon product recall payment",
    ],
    "close_account": [
        "How do I permanently close my Amazon account?",
        "What happens when I delete my Amazon account?",
        "Can I reopen my Amazon account after closing it?",
        "How to deactivate my Amazon account temporarily?",
        "What information is lost when I close my Amazon account?",
        "How long does it take to close an Amazon account?",
        "Can I close my Amazon account and keep my Kindle books?",
        "What happens to my Prime membership if I close my account?",
        "How to delete all my data from Amazon?",
        "Can I close just one Amazon marketplace account?",
        "What happens to my gift card balance when I close my account?",
        "How to request full data deletion with Amazon account closure?",
        "Can I transfer my order history before closing my account?",
        "What subscriptions need to be cancelled before closing my account?",
        "How do I close my Amazon account from the mobile app?",
        "What happens to my pending orders if I close my account?",
        "Can I close my Amazon account if I have an outstanding balance?",
        "How to close my child's Amazon account?",
        "What happens to my product reviews when I close my account?",
        "Can I close my Amazon account and open a new one?",
        "How to close my Amazon seller and buyer accounts separately?",
        "What happens to my Alexa devices if I close my account?",
        "Can I close my account but keep my Amazon Photos?",
        "How do I remove my payment methods before closing my account?",
        "What happens to my wish lists when I close my Amazon account?",
        "Can I get a refund for prepaid services when closing my account?",
        "How to close an Amazon Business account?",
        "What happens to shared household benefits when I close my account?",
        "Can I close my account if I have active Subscribe and Save?",
        "How to export my data before closing my Amazon account?",
        "What happens to my Audible credits when I close my account?",
        "Can I close my Amazon account from a different country?",
        "How long does Amazon retain my data after account closure?",
        "What happens to items in my cart when I close my account?",
        "Can I close my Amazon account if I have a pending return?",
        "How to close my Amazon account and all linked services?",
        "What happens to my Amazon Associates earnings if I close my account?",
        "Can I close my Amazon account if I'm under investigation?",
        "How do I confirm my Amazon account has been fully closed?",
        "What happens to my saved browsing history when I close my account?",
        "Can I close my account during a promotional period?",
        "How to close my Amazon Pharmacy account?",
        "What legal implications does closing my Amazon account have?",
        "Can someone else close my Amazon account on my behalf?",
        "How to close my Amazon account due to security concerns?",
        "What happens to my Prime Video watchlist when I close my account?",
        "Can I selectively close services while keeping my account?",
        "How to handle ongoing disputes before closing my Amazon account?",
        "What happens to my Amazon Music library when I close my account?",
        "Can I close my Amazon account and still use Amazon Web Services?",
        "How to notify Amazon of my reason for closing my account?",
        "What happens to my Amazon Smile donations when I close my account?",
        "Can I close my Amazon account if I have unredeemed promotional credits?",
        "How to manage linked accounts before closing my Amazon account?",
        "What evidence do I need that my Amazon account is fully closed?",
        "Can I keep my Prime benefits until the end of the billing cycle if I close my account?",
        "How to close my Amazon account due to too many data breaches?",
        "What happens to my Amazon trade-in credits when I close my account?",
        "Can I close my Amazon account if I have pending gift card claims?",
        "How to delink all devices before closing my Amazon account?",
        "What happens to my delivery preferences when I close my account?",
        "Can I close my Amazon account through customer service chat?",
        "How does closing my Amazon account affect my credit score?",
        "What happens to Amazon digital purchases tied to my closed account?",
        "Can I close my Amazon account and use a different email to create a new one?",
        "How to handle shared Kindle content before closing my account?",
        "What happens to my Prime wardrobe items if I close my account?",
        "Can I contest the closure of my Amazon account?",
        "How to close my Amazon account due to unauthorized access?",
        "What happens to automatic refills when I close my Amazon account?",
        "Can I close my Amazon Vendor Central account?",
        "How to verify the deletion of all personal data after closing my account?",
        "What happens to my Whole Foods linked benefits when I close my account?",
        "Can I close my Amazon account and keep my Goodreads account?",
        "How to handle pending cashback before closing my Amazon account?",
        "What happens to my Amazon registry when I close my account?",
    ],
    "investigate_unknown_charge": [
        "I see a charge from Amazon I don't recognize on my bank statement",
        "There's an unknown Amazon payment on my credit card",
        "I was charged by Amazon but didn't order anything",
        "How to track down an unrecognized Amazon charge?",
        "My bank statement shows a mysterious Amazon debit",
        "I found an unauthorized Amazon charge on my account",
        "How to investigate a suspicious charge from Amazon?",
        "There are two Amazon charges for the same amount",
        "I was charged by Amazon for something I already returned",
        "My credit card has an Amazon charge I can't identify",
        "How to find what an unknown Amazon charge is for?",
        "I see a pending Amazon charge but have no pending orders",
        "My bank statement shows multiple small Amazon charges",
        "I was charged by an Amazon service I never signed up for",
        "How do I check if an Amazon charge is legitimate?",
        "There's a recurring Amazon charge I don't understand",
        "My debit card shows an Amazon pre-authorization hold",
        "I noticed an Amazon charge from a different country",
        "How to match an Amazon charge to a specific order?",
        "I was double charged by Amazon for one purchase",
        "There's an Amazon digital charge I can't figure out",
        "My bank shows an Amazon hold that doesn't match any order",
        "I found an old Amazon charge I forgot about",
        "How do I dispute an unrecognized Amazon charge?",
        "My credit card bill has an Amazon subscription charge I didn't authorize",
        "There's a small Amazon test charge on my card",
        "I was charged by Amazon marketplace for an order I cancelled",
        "How to find details about a specific Amazon transaction?",
        "My bank statement lists a charge from AMZ or AMZN I don't recognize",
        "I see an Amazon Prime charge but I didn't sign up for Prime",
        "There's an unexpected Amazon Fresh charge on my card",
        "My card was charged by Amazon after I removed it from my account",
        "How do I look up an Amazon charge by transaction ID?",
        "I was charged for an Amazon trial I thought I cancelled",
        "My statement shows an Amazon charge with a weird reference number",
        "There's an Amazon charge that appeared days after my purchase",
        "I see a charge from Amazon but my order shows as free",
        "How to get a breakdown of an Amazon charge?",
        "My credit card has an Amazon charge for more than my order total",
        "There's an Amazon charge on my old credit card",
        "I was charged by Amazon for a gift someone else ordered",
        "How do I investigate partial Amazon charges on my statement?",
        "My bank shows multiple Amazon authorizations for one order",
        "There's a charge from Amazon digital services I don't recognize",
        "I was charged by Amazon but the order was never delivered",
        "How to dispute an Amazon charge with my credit card company?",
        "My statement shows an Amazon charge in a foreign currency",
        "There's an unexplained Amazon refund and recharge on my card",
        "I see a charge from Amazon Subscribe and Save I didn't expect",
        "How do I track an Amazon charge that doesn't match my orders?",
        "My card was charged by Amazon for a product I never received",
        "There's an Amazon charge on my joint account I can't identify",
        "I was charged for Amazon Kids+ but never signed up",
        "How to find out who made an Amazon purchase on my card?",
        "My bank flagged an unusual Amazon charge on my account",
        "There's a pending Amazon charge that has been there for days",
        "I see an Amazon Marketplace charge from an unknown seller",
        "How to get Amazon to explain a mysterious charge?",
        "My card shows an Amazon charge that was supposed to be cancelled",
        "There's an Amazon charge for shipping I was told would be free",
        "I was charged by Amazon for a quantity I didn't order",
        "How to review all charges from Amazon on my credit card?",
        "My statement has an Amazon charge that doesn't match any receipt",
        "There's an Amazon Pharmacy charge I wasn't expecting",
        "I see an Amazon Appstore charge I don't remember making",
        "How to verify if an Amazon charge came from my account?",
        "My card was charged by Amazon after I cancelled my account",
        "There's a small recurring Amazon charge I never noticed before",
        "I was charged for an Amazon warranty I didn't purchase",
        "How to report an unauthorized Amazon charge to customer service?",
        "My bank shows an Amazon refund and then a new charge right after",
        "There's an Amazon charge on my business credit card I can't trace",
        "I see an Amazon charge but my order history shows nothing",
        "How do I verify whether an unknown Amazon charge is a scam?",
        "My debit card shows a pending Amazon hold for an order I cancelled",
        "There's an Amazon charge on my parent's credit card from my account",
        "I was charged by Amazon for a pre-order I forgot about",
        "How to request a detailed statement from Amazon for all charges?",
        "My card has an Amazon charge that occurred at an unusual time",
        "There's a charge from Amazon that matches an old cancelled order",
        "I see an Amazon Music charge but I use Spotify",
        "How to identify if a charge is from Amazon or a third party?",
        "My card shows a charge from Amazon logistics I don't understand",
        "There's an Amazon charge for tax that seems too high",
        "I was charged by Amazon for a product review incentive I declined",
        "How to cross-reference Amazon charges with my order history?",
        "My statement has duplicate Amazon charges for different amounts",
        "There's an Amazon charge from a marketplace seller who refunded me",
        "I see an Amazon charge related to a household member's purchase",
        "How to set up alerts for all Amazon charges on my card?",
        "My bank shows an Amazon authorization reversal I don't understand",
        "There's an Amazon charge that appeared after a price adjustment",
        "I was charged by Amazon for a product that arrived damaged",
        "How to find old Amazon charges that don't show in recent orders?",
        "My card was charged by Amazon for a gift card I didn't buy",
        "There's an Amazon charge labeled as 'adjustment' on my statement",
    ],
    "report_missing_package": [
        "My Amazon package was marked delivered but I never got it",
        "My order shows delivered but nothing was at my door",
        "I think someone stole my Amazon package",
        "How to report a missing Amazon delivery?",
        "My package says delivered but it's not here",
        "The tracking says my Amazon order was delivered yesterday but I didn't receive it",
        "How do I get a refund for an Amazon package that never arrived?",
    ],
}

new_records = []
for intent, templates in EXTRA_TEMPLATES.items():
    current = counts.get(intent, 0)
    needed = max(0, target_per - current)
    available = [t for t in templates if t.strip().lower() not in existing]
    take = min(needed, len(available))
    if take > 0:
        selected = random.sample(available, take) if take < len(available) else available[:take]
        for q in selected:
            new_records.append({"question": q, "intent label": intent})
            existing.add(q.strip().lower())
        print(f"  {intent}: +{take} (was {current}, now {current+take})")

print(f"\nAdded {len(new_records)} more queries")

new_df = pd.DataFrame(new_records)
v2_final = pd.concat([v2_df, new_df], ignore_index=True)
v2_final = v2_final.sample(frac=1, random_state=42).reset_index(drop=True)
v2_final = v2_final.drop_duplicates(subset=["question"], keep="first")

eval_qs = set(eval_df["question"].str.lower().str.strip())
overlap = v2_final["question"].str.lower().str.strip().isin(eval_qs)
if overlap.sum() > 0:
    v2_final = v2_final[~overlap]

v2_final.to_csv(V2_FILE, index=False)
print(f"\nFinal v2: {len(v2_final)} queries")

counts = v2_final["intent label"].value_counts()
print(f"Min: {counts.min()} ({counts.idxmin()})")
print(f"Max: {counts.max()} ({counts.idxmax()})")
print(f"Mean: {counts.mean():.1f}")
print(f"All 34 intents covered: {len(counts) == 34}")
print("Done!")
